using System.Windows;
using EnhancedBank.Model;

namespace EnhancedBank.View;

public partial class AdminWindow : Window
{
	public AdminWindow()
	{
		InitializeComponent();
		
		Grid.IsReadOnly = false;
		Grid.ItemsSource = App.Current.Db.Employees.ToList();
	}

	private void OnLeaveButtonClick(object sender, RoutedEventArgs e)
	{
		Close();
	}

	private void OnGridAutoGeneratedColumns(object? sender, EventArgs e)
	{
		Grid.Columns[0].Visibility = Visibility.Hidden;
	}
}