using System.Windows;

namespace EnhancedBank.View;

public partial class UserDataWindow : Window
{
	public UserDataWindow()
	{
		InitializeComponent();
		
		Grid.IsReadOnly = true;
		Grid.ItemsSource = App.Current.Db.Employees.ToList();
	}

	private void OnLeaveButtonClick(object sender, RoutedEventArgs e)
	{
		Close();
	}
	
	private void OnGridAutoGeneratedColumns(object? sender, EventArgs e)
	{
		Grid.Columns[0].Visibility = Visibility.Hidden;
	}
}